/**
 * Did the model move?
 *
 * A change to a coefficient in `model-params.ts` reprices every trip in the
 * product, and until the fares were checked in, the diff showed only the
 * coefficient. This test fails when the committed fares stop matching, and
 * prints which trips moved and by how much.
 *
 * It is not a claim that the numbers are right — nothing here can make one,
 * and `docs/CALIBRATION.md` says so at length. It is a claim that changing
 * them was deliberate.
 */

import { readFileSync } from "node:fs";

import { describe, expect, it } from "vitest";

import { MODEL_VERSION } from "@/lib/sources/ratecard/model-params";
import {
  SNAPSHOT_PATH,
  buildSnapshot,
  type Snapshot,
  type SnapshotRow,
} from "@/../scripts/model-snapshot";

const committed: Snapshot = JSON.parse(readFileSync(SNAPSHOT_PATH, "utf8"));
const current = buildSnapshot();

const key = (r: SnapshotRow) => `${r.leg} | ${r.when} | ${r.product}`;

describe("the committed fares", () => {
  it("still cover the same trips", () => {
    expect(current.rows.map(key)).toEqual(committed.rows.map(key));
  });

  /*
   * The message is the feature. A bare "expected 71.6 to be 70.1" sends
   * somebody hunting; a list of which trips moved and by how much is enough
   * to decide whether it was intended in one read.
   */
  it("have not moved", () => {
    const byKey = new Map(committed.rows.map((r) => [key(r), r]));
    const moved: string[] = [];

    for (const row of current.rows) {
      const was = byKey.get(key(row));
      if (!was) continue;
      if (was.low !== row.low || was.high !== row.high) {
        const delta = row.low - was.low;
        const pct = was.low === 0 ? 0 : (delta / was.low) * 100;
        moved.push(
          `  ${key(row).padEnd(46)} $${was.low.toFixed(2)}–${was.high.toFixed(2)}` +
            ` → $${row.low.toFixed(2)}–${row.high.toFixed(2)}` +
            `  (${delta >= 0 ? "+" : ""}${delta.toFixed(2)}, ${pct >= 0 ? "+" : ""}${pct.toFixed(1)}%)`,
        );
      }
    }

    expect(
      moved.length,
      moved.length === 0
        ? ""
        : `\n\n${moved.length} of ${current.rows.length} fares moved:\n\n${moved.slice(0, 25).join("\n")}` +
            (moved.length > 25 ? `\n  …and ${moved.length - 25} more` : "") +
            `\n\nIf that was intended: bump MODEL_VERSION (the trip log pools observations by it),` +
            ` then run \`npm run snapshot:model\` and commit the new fares with the change.\n`,
    ).toBe(0);
  });

  /*
   * A snapshot regenerated without bumping the version would pool two
   * estimators' observations under one name in every rider's trip log.
   */
  it("were generated by the model version that is running", () => {
    expect(
      committed.modelVersion,
      "the snapshot was taken by a different model — regenerate it, or the fares above are not this model's",
    ).toBe(MODEL_VERSION);
  });

  it("cover every product, leg and time the generator names", () => {
    const products = new Set(committed.rows.map((r) => r.product));
    const legs = new Set(committed.rows.map((r) => r.leg));
    const whens = new Set(committed.rows.map((r) => r.when));
    expect(products.size).toBeGreaterThanOrEqual(5);
    expect(legs.size).toBeGreaterThanOrEqual(5);
    expect(whens.size).toBeGreaterThanOrEqual(5);
    /* One wet case per leg and time, or the weather path is untested here. */
    expect(committed.rows.some((r) => r.weather > 1)).toBe(true);
  });
});
